name: Android Release Unsigned

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: '17'
      - uses: gradle/actions/setup-gradle@v6
      - run: chmod +x ./gradlew
      - run: ./gradlew :app:assembleRelease
      - uses: actions/upload-artifact@v4
        with:
          name: miku-moe-release-unsigned-apk
          path: app/build/outputs/apk/release/*.apk
